# Generated by Django 5.1.7 on 2025-03-22 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Черновик'), ('PROCESS', 'В процессе'), ('COMPLETE', 'Выполнен')], default='DRAFT')),
                ('address', models.CharField(max_length=256, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderProducts',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
