# Generated by Django 5.2.1 on 2025-05-31 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderproducts',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
