# Generated by Django 5.1.7 on 2025-03-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='products',
            name='stored_amount',
            field=models.IntegerField(default=0),
        ),
    ]
