# Generated by Django 5.2.1 on 2025-05-31 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_image_delete_productimages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.CharField(default='images/placeholder.png', max_length=100),
        ),
    ]
